services:
  client:
    build: ./app-client
    container_name: app-client-cnt
    ports:
      - 3000:3000
    volumes:
      - ./app-client:/app-client
  postgres_db:
    image: postgres:16.1
    container_name: exp-postgres-cnt
    environment:
      POSTGRES_PASSWORD: app-pass
      POSTGRES_USER: app-user
      POSTGRES_DB: app_db
    ports:
      - 5000:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
volumes:
  postgres_db:
